from __future__ import annotations

from typing import Any, List

from pydantic import BaseModel, Field


class VoterQueryRequest(BaseModel):
    sql: str = Field(..., description="SELECT-only SQL generated by the agent")
    constituency_id: str = Field(
        ..., description="Slug; enforced against the caller's claims server-side"
    )


class VoterQueryResponse(BaseModel):
    columns: List[str]
    rows: List[List[Any]]
    row_count: int
    truncated: bool


class SchemaResponse(BaseModel):
    tables: List[str]
    schema_text: str
    samples: dict
