"""
Application settings.
Reads from environment variables / Secret Manager in production.
"""

from __future__ import annotations

from functools import lru_cache
from typing import Optional

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    # Environment
    env: str = "dev"  # dev | staging | prod
    region: str = "asia-south1"

    # GCS data bucket (private, per-environment)
    gcs_data_bucket: str = "booth-agent-data-dev"

    # Local fallback for development (path to a folder that mirrors GCS layout)
    # e.g. legacy-data/ or a local copy of gs://.../gyanpur/
    local_data_root: Optional[str] = None

    # Firebase
    firebase_project_id: Optional[str] = None
    # Path to service-account JSON, or leave empty to use Application Default Credentials
    firebase_credentials_path: Optional[str] = None

    # Vertex AI Agent Engine
    agent_engine_resource_name: Optional[str] = None
    # For local/dev: call agents in-process instead of Agent Engine
    agent_local_mode: bool = True

    # Sarvam voice
    sarvam_api_key: str = ""
    sarvam_stt_model: str = "saaras:v3"
    sarvam_stt_mode: str = "transcribe"
    sarvam_tts_model: str = "bulbul:v3"
    sarvam_tts_speaker: str = "shubh"
    sarvam_tts_pace: float = 1.0
    sarvam_tts_language: str = "hi-IN"

    # Gemini (only needed for local agent mode; Agent Engine uses Workload Identity)
    gemini_api_key: str = ""
    gemini_model: str = "gemini-2.5-flash"

    # Backend public URL (used by ADK tools when calling back into this service)
    backend_url: str = "http://localhost:8080"

    # Manifest of constituencies (generated by Cloud Build, or local path)
    constituencies_manifest_path: str = "constituencies/manifest.json"


@lru_cache
def get_settings() -> Settings:
    return Settings()
